# Generated by Django 2.2.6 on 2019-10-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('eci_id', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('date_of_joining', models.DateField()),
                ('address', models.CharField(max_length=1000)),
                ('prior_experience', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(max_length=2)),
                ('no_of_events_conducted', models.IntegerField(max_length=5)),
                ('rating', models.IntegerField(max_length=2)),
                ('digital_badge', models.IntegerField(max_length=2)),
                ('id_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECI.Details')),
            ],
        ),
    ]
