# Generated by Django 2.2.6 on 2019-10-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='prior_experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='digital_badge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='no_of_events_conducted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
