# Generated by Django 2.2.6 on 2019-11-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECI', '0002_auto_20191028_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='date_of_joining',
        ),
    ]
