# Generated by Django 2.2.6 on 2019-11-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI', '0003_remove_details_date_of_joining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('pic', models.ImageField(upload_to='pics')),
                ('completion_status', models.BooleanField(default=False)),
            ],
        ),
    ]
