# Generated by Django 2.2.6 on 2019-11-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI', '0004_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='url_link',
            field=models.URLField(default='https://youtu.be/OTmQOjsl0eg'),
            preserve_default=False,
        ),
    ]
