# Generated by Django 2.2.6 on 2019-11-05 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ECI', '0005_images_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='id_details',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.CASCADE, to='ECI.Details'),
            preserve_default=False,
        ),
    ]
