# Generated by Django 2.2.6 on 2019-11-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECI', '0007_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='id_details',
        ),
        migrations.AddField(
            model_name='progress',
            name='email',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
